start_date : 2024 -01 -01
currencies :
- eur
- usd
- jpy
- chf
output_folder : output_data
save_to_file : true
save_to_db : false
db_type : sqlite
sqlit e_da taba se_f ile : data . sqlite
db_host : xxx
dh_port : xxx
db_name : xxx
db_user : xxx
db_pass : xxx